name: multibags
specificationFileName: openapi_grupo06.json
authenticationCommands:
  default: sh apis/multibags/scripts/auth.sh
# the reset command below is not yet being called automatically it is planned for next release of restTestGen,
# but you can run it manually
resetBeforeTesting: true
resetCommand: "sh apis/multibags/scripts/reset.sh 10 500"